import:
  - nary_tucker

job:
  type: train
  device: cpu

dataset:
  name: jf17k3

model: nary_tucker

train:
  type: nary_negative_sampling
  max_epochs: 3
  batch_size: 64
  optimizer:
    default:
      type: Adagrad
      args:
        lr: 0.1

nary_negative_sampling:
  num_negatives: 5
  corrupt_all_arguments: True
